export const constants = {
  GET_VENUES: 'GET_VENUES',
  GET_CAKES: 'GET_CAKES',
  GET_CARTOON_HEROES: 'GET_CARTOON_HEROES',
  GET_DECORATIONS: 'GET_DECORATIONS',
  GET_PHOTOGRAPHERS: 'GET_PHOTOGRAPHERS',
  GET_GAME_SHOWS: 'GET_GAME_SHOWS',
  UPDATE_JUBILEE_INFO: 'UPDATE_JUBILEE_INFO',
  UPDATE_SINGLE_JUBILEE_INFO: 'UPDATE_SINGLE_JUBILEE_INFO',
  SELECT_VENUE: 'SELECT_VENUE',
  DESELECT_VENUE: 'DESELECT_VENUE',
  SELECT_SERVICE: 'SELECT_SERVICE',
  DESELECT_SERVICE: 'DESELECT_SERVICE',
};
