export const constants = {
  GET_RESTAURANTS: 'GET_RESTAURANTS',
  GET_CAKES: 'GET_CAKES',
  GET_CARTOON_HEROES: 'GET_CARTOON_HEROES',
  GET_DECORATIONS: 'GET_DECORATIONS',
  GET_PHOTOGRAPHERS: 'GET_PHOTOGRAPHERS',
  GET_GAME_SHOWS: 'GET_GAME_SHOWS',
};
